# Generated by Django 3.2 on 2022-04-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='complete',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
